blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/dasupradyumna/midnight.nvim/discussions
    about: Please explore conversations in Discussions before submitting an issue
